version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements.txt  # Ensure you have Sphinx listed in this file
    - method: pip
      path: .

sphinx:
  configuration: source/conf.py  # This should match your project structure

formats:
  - pdf  # Optionally, you can also add epub if desired

# Optionally, if you don't want additional formats, you can omit the formats section altogether
# formats:
#   - pdf
#   - epub
