# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation with Sphinx
sphinx:
  configuration: source/conf.py  # Adjusted to your project structure where conf.py is under source/

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - html
  - pdf  # Add pdf if you also want to generate PDFs for your documentation

# Install the Python dependencies required to build your documentation
python:
  install:
    - requirements: requirements.txt  # Ensure your requirements.txt has Sphinx and dependencies
    - method: pip
      path: .  # This will install your package and dependencies if needed

# Optionally, ignore certain files or directories from the build
#build:
#  ignore:
#    - README.md  # You can add files here to exclude from the documentation build if needed

# Optionally add any environment variables your documentation build might need
# Note: You only need this section if your documentation requires external environment variables (not typical for Sphinx docs).
#build:
#  environment:
#    AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}  # Example

# Add settings for how Read the Docs runs the build process
# (Optional but can be useful to manage the build process more carefully)
build:
  jobs: 2  # Number of concurrent jobs, can adjust based on need
